### ISSUE TITLE
save user to DB with all additional data (address, city, PSC, school, school address)

### ISSUE THREAD

**Issue by timbez** [ThoraX-SVK/Webte2#67]
To implelement a method (preferably in database/userUtils.php) to save User and all additional data that comes in with the CSV file (see issue title).  
related issue - #24

**Comment by ThoraX-SVK** [comment]
Could you please provide some sort of array that will be representing input data? Based on DB Address have many fields, so it should be something like "userCity" => "Bratislava", schoolCity => "Bratislava"

Thanks @timbez

**Comment by timbez** [comment]
The array might look something like this:
$userData= array (
            "surname" => "PRIEZV",
            "name" =>"MENO",
            "email" => "EMAIL",
            "password" => "heslo",
            "schoolName" => "SKOLA",
            "schoolCity" => "Namestovo",
            "schoolStreet" => "SKOLAAD",
            "schoolStreetNo" => "456",
            "schoolPSC" => "84555",
            "userStreet" => "ulica",
            "userStreetNo" => "12",
            "userPSC" => "PSC",
            "userCity" => "MESTO"
        );
Is that sufficient?

**Comment by ThoraX-SVK** [comment]
To that array, we also need to include "passwordConfirm" => "heslo"

**Comment by ThoraX-SVK** [comment]
Also, it will be needed to add "SchoolState" and "UserState".
As note, it is VERY important, to set full array first, with keys and values with null, this can be done via something like:
makeEmptyUserArray()

Because, if key is not set, it will be problematic, we will be getting exceptions and so on. Null keys should be okay in DB, and parameters that cant be null are checked somewhere else.

**Comment by ThoraX-SVK** [comment]
Done
