### ISSUE TITLE
Provide changed sql_dump file

### ISSUE THREAD

**Issue by ThoraX-SVK** [ThoraX-SVK/Webte2#79]
Small changes were made.

**Comment by Liblink** [comment]
@ThoraX-SVK 
proposed changes:
table "route" has only distance, but not starting and ending point (without them google maps cant print route)

user can have only one active route, so i think that table "UserActiveRoute" is not necessary, and should be kept as users atribute instead

**Comment by ThoraX-SVK** [comment]
@Liblink  Yes, that are good ideas, will do it today

**Comment by Liblink** [comment]
@ThoraX-SVK 
But that may also require some changes in newRouteController.php, because it now only handles distance of the route, but not start and end point. And in that case, should "newRoutePage" also contain map, where user sets starting and ending point and gets the route distance from google maps? If that is correct, then "newRoutePage" issue should be updated.

**Comment by ThoraX-SVK** [comment]
Yes, It will be needed to update both controller, and saving route to DB functions. Should be done by midnight.

**Comment by ThoraX-SVK** [comment]
Could you please write down all required fields needed for you to construct page?

**Comment by Liblink** [comment]
Table "News" should contain:
-"Header"   VARCHAR 80
-"Content"  VARCHAR 1000 (or other big value, so whole content of the news message can be stored here)
-"Added"    CURRENT_TIMESTAMP

**Comment by Liblink** [comment]
CURRENT_DATE will be enough
